if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

set(MODEL_CPP "${SOURCE_DIR}/src/engine/models/ModelSystem.cpp")
if(NOT EXISTS "${MODEL_CPP}")
    message(FATAL_ERROR "Model safety guard failed: engine model system is missing")
endif()
file(READ "${MODEL_CPP}" MODEL_SYSTEM)

if(MODEL_SYSTEM MATCHES "(FileExists|LoadModel|LoadModelAnimations)\\([^\\)]*\\.data\\(")
    message(FATAL_ERROR "Model safety guard failed: C APIs must not receive raw string_view::data() paths")
endif()
if(NOT MODEL_SYSTEM MATCHES "const std::string assetPath\\{")
    message(FATAL_ERROR "Model safety guard failed: model paths must be copied into null-terminated std::string values")
endif()
if(NOT MODEL_SYSTEM MATCHES "releasePrototypeAfterInstance && instance->ownsIndependentModel\\(\\)")
    message(FATAL_ERROR "Model safety guard failed: prototype release must be limited to independent owning instances")
endif()

message(STATUS "Model safety guard passed: model paths and prototype release invariant are hardened.")
