if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()

function(read_required relative_path out_var)
    set(full_path "${SOURCE_DIR}/${relative_path}")
    if(NOT EXISTS "${full_path}")
        message(FATAL_ERROR "Screen flow guard missing required file: ${relative_path}")
    endif()
    file(READ "${full_path}" contents)
    set(${out_var} "${contents}" PARENT_SCOPE)
endfunction()

read_required("src/game/screens/loading/LoadingScreen.cpp" LOADING_SCREEN)
read_required("src/game/screens/main_menu/MainMenuScreen.cpp" MAIN_MENU_SCREEN)
read_required("src/game/screens/main_menu/MainMenuScreen.hpp" MAIN_MENU_HEADER)
read_required("src/game/screens/join/JoinScreen.cpp" JOIN_SCREEN)
read_required("src/game/screens/GameScreenCatalog.hpp" GAME_SCREEN_CATALOG)
read_required("src/engine/ui/typed/ScreenTypes.hpp" SCREEN_TYPES)
read_required("src/game/screens/GameScreenIds.hpp" GAME_SCREEN_IDS)

if(NOT LOADING_SCREEN MATCHES "queueReplace<MainMenuScreen>\\(")
    message(FATAL_ERROR "Screen flow guard failed: normal loading flow must land on MainMenuScreen first")
endif()
if(LOADING_SCREEN MATCHES "queueReplace<(JoinScreen|GamePlayScreen|FarmScreen)>\\(")
    message(FATAL_ERROR "Screen flow guard failed: LoadingScreen must not bypass the main menu")
endif()
if(NOT MAIN_MENU_SCREEN MATCHES "queueReplace<JoinScreen>\\(")
    message(FATAL_ERROR "Screen flow guard failed: MainMenuScreen must route New Game/Continue into JoinScreen after the shader transition")
endif()
if(MAIN_MENU_SCREEN MATCHES "queueReplace<(GamePlayScreen|FarmScreen)>\\(")
    message(FATAL_ERROR "Screen flow guard failed: MainMenuScreen must not enter gameplay directly")
endif()
if(NOT JOIN_SCREEN MATCHES "queueReplace<GamePlayScreen>\\(")
    message(FATAL_ERROR "Screen flow guard failed: JoinScreen must enter GamePlayScreen")
endif()
if(NOT MAIN_MENU_HEADER MATCHES "m_joinTransitionQueued")
    message(FATAL_ERROR "Screen flow guard failed: MainMenuScreen must guard duplicate JoinScreen transitions")
endif()
if(GAME_SCREEN_CATALOG MATCHES "FarmScreen|ScreenId::Farm|game/screens/farm")
    message(FATAL_ERROR "Screen flow guard failed: stale FarmScreen route/catalog reference remains")
endif()
if(SCREEN_TYPES MATCHES "Farm|Join|GamePlay")
    message(FATAL_ERROR "Screen flow guard failed: engine ScreenId must stay generic and game-name free")
endif()
if(GAME_SCREEN_IDS MATCHES "Farm")
    message(FATAL_ERROR "Screen flow guard failed: stale Farm screen ID remains")
endif()
if(NOT GAME_SCREEN_IDS MATCHES "inline constexpr auto Join" OR NOT GAME_SCREEN_IDS MATCHES "inline constexpr auto GamePlay")
    message(FATAL_ERROR "Screen flow guard failed: game screen IDs must include Join and GamePlay")
endif()

message(STATUS "Screen flow guard passed: loading reaches menu, menu reaches Join, Join reaches GamePlay.")
