if(NOT DEFINED SRC_DIR)
    message(FATAL_ERROR "SRC_DIR is required")
endif()
if(NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "OUTPUT_DIR is required")
endif()

file(GLOB_RECURSE TYPED_MODULE_HEADERS
    "${SRC_DIR}/*.hpp"
    "${SRC_DIR}/*.h"
)

set(EVENT_INCLUDES "")
set(SERVICE_INCLUDES "")
set(ASSET_INCLUDES "")
set(SHADER_INCLUDES "")
set(EVENT_ALIASES "")
set(SERVICE_ALIASES "")
set(ASSET_ALIASES "")
set(SHADER_ALIASES "")

foreach(HEADER IN LISTS TYPED_MODULE_HEADERS)
    file(READ "${HEADER}" CONTENTS)
    string(REGEX MATCHALL "BIOFUEL_TYPED_MODULE\\([ \t\r\n]*[A-Za-z_]+[ \t\r\n]*,[ \t\r\n]*[A-Za-z_][A-Za-z0-9_]*[ \t\r\n]*,[ \t\r\n]*[^\\)\r\n]+\\)" MARKERS "${CONTENTS}")
    if(NOT MARKERS)
        set(MARKERS "")
    endif()

    file(RELATIVE_PATH REL_HEADER "${SRC_DIR}" "${HEADER}")
    string(REPLACE "\\" "/" REL_HEADER "${REL_HEADER}")

    foreach(MARKER IN LISTS MARKERS)
        string(REGEX REPLACE "BIOFUEL_TYPED_MODULE\\([ \t\r\n]*([A-Za-z_]+)[ \t\r\n]*,[ \t\r\n]*([A-Za-z_][A-Za-z0-9_]*)[ \t\r\n]*,[ \t\r\n]*([^\\)\r\n]+)\\)" "\\1;\\2;\\3" PARTS "${MARKER}")
        list(GET PARTS 0 CATEGORY)
        list(GET PARTS 1 ALIAS)
        list(GET PARTS 2 MODULE)
        string(STRIP "${MODULE}" MODULE)
        if(MODULE STREQUAL "..." OR MODULE STREQUAL "MODULE_TYPE" OR MODULE MATCHES "MODULE_NAME|TAG_TYPE|REGISTRY_ALIAS")
            continue()
        endif()

        if(CATEGORY STREQUAL "event")
            list(APPEND EVENT_INCLUDES "${REL_HEADER}")
            list(APPEND EVENT_ALIASES "${ALIAS}|${MODULE}")
        elseif(CATEGORY STREQUAL "service")
            list(APPEND SERVICE_INCLUDES "${REL_HEADER}")
            list(APPEND SERVICE_ALIASES "${ALIAS}|${MODULE}")
        elseif(CATEGORY STREQUAL "asset")
            list(APPEND ASSET_INCLUDES "${REL_HEADER}")
            list(APPEND ASSET_ALIASES "${ALIAS}|${MODULE}")
        elseif(CATEGORY STREQUAL "shader")
            list(APPEND SHADER_INCLUDES "${REL_HEADER}")
            list(APPEND SHADER_ALIASES "${ALIAS}|${MODULE}")
        endif()
    endforeach()

    if(REL_HEADER MATCHES "^engine/runtime/typed/.*Declare\\.hpp$" OR REL_HEADER STREQUAL "engine/graphics/shaders/ShaderModule.hpp")
        set(HELPER_MARKERS "")
    else()
        string(REGEX MATCHALL "BIOFUEL_(EVENT|SERVICE|ASSET|SHADER)_MODULE\\([ \t\r\n]*[A-Za-z_][A-Za-z0-9_]*[ \t\r\n]*,[ \t\r\n]*[A-Za-z_][A-Za-z0-9_]*" HELPER_MARKERS "${CONTENTS}")
    endif()
    foreach(MARKER IN LISTS HELPER_MARKERS)
        string(REGEX REPLACE "BIOFUEL_([A-Z]+)_MODULE\\([ \t\r\n]*([A-Za-z_][A-Za-z0-9_]*)[ \t\r\n]*,[ \t\r\n]*([A-Za-z_][A-Za-z0-9_]*)" "\\1;\\2;\\3" PARTS "${MARKER}")
        list(GET PARTS 0 KIND)
        list(GET PARTS 1 MODULE_NAME)
        list(GET PARTS 2 ALIAS)
        if(MODULE_NAME STREQUAL "MODULE_NAME")
            continue()
        endif()

        if(KIND STREQUAL "EVENT")
            list(APPEND EVENT_INCLUDES "${REL_HEADER}")
            list(APPEND EVENT_ALIASES "${ALIAS}|::biofuel::engine::runtime::typed::events::${MODULE_NAME}")
        elseif(KIND STREQUAL "SERVICE")
            list(APPEND SERVICE_INCLUDES "${REL_HEADER}")
            list(APPEND SERVICE_ALIASES "AppServiceRegistry|::biofuel::engine::runtime::typed::services::${MODULE_NAME}")
        elseif(KIND STREQUAL "ASSET")
            list(APPEND ASSET_INCLUDES "${REL_HEADER}")
            list(APPEND ASSET_ALIASES "${ALIAS}|::biofuel::engine::runtime::typed::assets::${MODULE_NAME}")
        elseif(KIND STREQUAL "SHADER")
            list(APPEND SHADER_INCLUDES "${REL_HEADER}")
            list(APPEND SHADER_ALIASES "ShaderAssetRegistry|::biofuel::engine::runtime::typed::shaders::${MODULE_NAME}")
        endif()
    endforeach()
endforeach()

list(REMOVE_DUPLICATES EVENT_INCLUDES)
list(REMOVE_DUPLICATES SERVICE_INCLUDES)
list(REMOVE_DUPLICATES ASSET_INCLUDES)
list(REMOVE_DUPLICATES SHADER_INCLUDES)

function(write_includes OUT_VAR)
    set(TEXT "")
    foreach(INCLUDE IN LISTS ARGN)
        string(APPEND TEXT "#include \"${INCLUDE}\"\n")
    endforeach()
    set(${OUT_VAR} "${TEXT}" PARENT_SCOPE)
endfunction()

function(write_aliases OUT_VAR ALIAS_ROWS APP_REGISTRY)
    set(ALIASES "")
    set(GROUPS "")
    foreach(ROW IN LISTS ${ALIAS_ROWS})
        string(REPLACE "|" ";" PARTS "${ROW}")
        list(GET PARTS 0 ALIAS)
        list(GET PARTS 1 MODULE)
        list(APPEND GROUPS "${ALIAS}")
        list(APPEND MODULES_${ALIAS} "${MODULE}")
    endforeach()
    list(REMOVE_DUPLICATES GROUPS)
    foreach(GROUP IN LISTS GROUPS)
        set(MODULE_REGISTRIES "")
        foreach(MODULE IN LISTS "MODULES_${GROUP}")
            if(MODULE_REGISTRIES STREQUAL "")
                set(MODULE_REGISTRIES "${MODULE}::Registry")
            else()
                string(APPEND MODULE_REGISTRIES ",\n    ${MODULE}::Registry")
            endif()
        endforeach()
        string(APPEND ALIASES "using ${GROUP} = biofuel::typed::RegistryConcatT<\n    ${MODULE_REGISTRIES}>;\n")
    endforeach()

    if(NOT APP_REGISTRY STREQUAL "")
        set(APP_GROUPS "")
        foreach(GROUP IN LISTS GROUPS)
            if(NOT GROUP STREQUAL APP_REGISTRY)
                if(APP_GROUPS STREQUAL "")
                    set(APP_GROUPS "${GROUP}")
                else()
                    string(APPEND APP_GROUPS ",\n    ${GROUP}")
                endif()
            endif()
        endforeach()
        if(NOT APP_GROUPS STREQUAL "")
            string(APPEND ALIASES "using ${APP_REGISTRY} = biofuel::typed::RegistryConcatT<\n    ${APP_GROUPS}>;\n")
        endif()
    endif()

    set(${OUT_VAR} "${ALIASES}" PARENT_SCOPE)
endfunction()

file(MAKE_DIRECTORY "${OUTPUT_DIR}/engine/runtime/typed/generated")

write_includes(EVENT_INCLUDE_TEXT ${EVENT_INCLUDES})
write_aliases(EVENT_ALIAS_TEXT EVENT_ALIASES "AppEventRegistry")
file(WRITE "${OUTPUT_DIR}/engine/runtime/typed/generated/GeneratedEventRegistry.hpp" "#pragma once\n\n#include \"engine/core/typed/Meta.hpp\"\n${EVENT_INCLUDE_TEXT}\nnamespace biofuel::engine::runtime::typed {\n${EVENT_ALIAS_TEXT}static_assert(AppEventRegistry::valid());\n} // namespace biofuel::engine::runtime::typed\n")

write_includes(SERVICE_INCLUDE_TEXT ${SERVICE_INCLUDES})
write_aliases(SERVICE_ALIAS_TEXT SERVICE_ALIASES "")
file(WRITE "${OUTPUT_DIR}/engine/runtime/typed/generated/GeneratedServiceRegistry.hpp" "#pragma once\n\n#include \"engine/core/typed/Meta.hpp\"\n${SERVICE_INCLUDE_TEXT}\nnamespace biofuel::engine::runtime::typed {\n${SERVICE_ALIAS_TEXT}static_assert(AppServiceRegistry::valid());\ntemplate<typename TRegistry>\nclass GameServices;\nusing AppServices = GameServices<AppServiceRegistry>;\n} // namespace biofuel::engine::runtime::typed\n")

write_includes(ASSET_INCLUDE_TEXT ${ASSET_INCLUDES})
write_aliases(ASSET_ALIAS_TEXT ASSET_ALIASES "AppAssetRegistry")
file(WRITE "${OUTPUT_DIR}/engine/runtime/typed/generated/GeneratedAssetRegistry.hpp" "#pragma once\n\n#include \"engine/core/typed/Meta.hpp\"\n${ASSET_INCLUDE_TEXT}\nnamespace biofuel::engine::runtime::typed {\n${ASSET_ALIAS_TEXT}static_assert(AppAssetRegistry::valid());\n} // namespace biofuel::engine::runtime::typed\n")

write_includes(SHADER_INCLUDE_TEXT ${SHADER_INCLUDES})
write_aliases(SHADER_ALIAS_TEXT SHADER_ALIASES "")
file(WRITE "${OUTPUT_DIR}/engine/runtime/typed/generated/GeneratedShaderRegistry.hpp" "#pragma once\n\n#include \"engine/core/typed/Meta.hpp\"\n${SHADER_INCLUDE_TEXT}\nnamespace biofuel::engine::runtime::typed {\n${SHADER_ALIAS_TEXT}static_assert(ShaderAssetRegistry::valid());\n} // namespace biofuel::engine::runtime::typed\n")
