if(NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "OUTPUT_DIR is required")
endif()
if(NOT DEFINED REQUIREMENTS_FILE)
    message(FATAL_ERROR "REQUIREMENTS_FILE is required")
endif()

set(UV_VERSION "latest")
set(UV_DIR "${OUTPUT_DIR}/uv")
set(VENV_DIR "${OUTPUT_DIR}/.venv")
file(MAKE_DIRECTORY "${UV_DIR}")

find_program(SYSTEM_UV uv)
if(SYSTEM_UV)
    set(UV_EXECUTABLE "${SYSTEM_UV}")
else()
    if(WIN32)
        set(UV_ARCHIVE "${UV_DIR}/uv.zip")
        set(UV_URL "https://github.com/astral-sh/uv/releases/${UV_VERSION}/download/uv-x86_64-pc-windows-msvc.zip")
        set(UV_EXECUTABLE "${UV_DIR}/uv.exe")
    elseif(APPLE)
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
            set(UV_PLATFORM "aarch64-apple-darwin")
        else()
            set(UV_PLATFORM "x86_64-apple-darwin")
        endif()
        set(UV_ARCHIVE "${UV_DIR}/uv.tar.gz")
        set(UV_URL "https://github.com/astral-sh/uv/releases/${UV_VERSION}/download/uv-${UV_PLATFORM}.tar.gz")
        set(UV_EXECUTABLE "${UV_DIR}/uv-${UV_PLATFORM}/uv")
    else()
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
            set(UV_PLATFORM "aarch64-unknown-linux-gnu")
        else()
            set(UV_PLATFORM "x86_64-unknown-linux-gnu")
        endif()
        set(UV_ARCHIVE "${UV_DIR}/uv.tar.gz")
        set(UV_URL "https://github.com/astral-sh/uv/releases/${UV_VERSION}/download/uv-${UV_PLATFORM}.tar.gz")
        set(UV_EXECUTABLE "${UV_DIR}/uv-${UV_PLATFORM}/uv")
    endif()

    if(NOT EXISTS "${UV_EXECUTABLE}")
        message(STATUS "Downloading uv from ${UV_URL}")
        file(DOWNLOAD "${UV_URL}" "${UV_ARCHIVE}" SHOW_PROGRESS TLS_VERIFY ON STATUS UV_DOWNLOAD_STATUS)
        list(GET UV_DOWNLOAD_STATUS 0 UV_DOWNLOAD_CODE)
        if(NOT UV_DOWNLOAD_CODE EQUAL 0)
            list(GET UV_DOWNLOAD_STATUS 1 UV_DOWNLOAD_MESSAGE)
            message(FATAL_ERROR "Failed to download uv: ${UV_DOWNLOAD_MESSAGE}")
        endif()
        file(ARCHIVE_EXTRACT INPUT "${UV_ARCHIVE}" DESTINATION "${UV_DIR}")
        if(WIN32 AND EXISTS "${UV_DIR}/uv-x86_64-pc-windows-msvc/uv.exe")
            file(COPY_FILE "${UV_DIR}/uv-x86_64-pc-windows-msvc/uv.exe" "${UV_EXECUTABLE}" ONLY_IF_DIFFERENT)
        endif()
    endif()
endif()

if(NOT EXISTS "${UV_EXECUTABLE}")
    message(FATAL_ERROR "uv executable was not found after setup")
endif()

set(ENV{UV_PYTHON_INSTALL_DIR} "${OUTPUT_DIR}/python-installs")
if(WIN32)
    set(PYTHON_EXE "${VENV_DIR}/Scripts/python.exe")
else()
    set(PYTHON_EXE "${VENV_DIR}/bin/python")
endif()

if(NOT EXISTS "${PYTHON_EXE}")
    execute_process(
        COMMAND "${UV_EXECUTABLE}" venv --python 3.12 "${VENV_DIR}"
        RESULT_VARIABLE VENV_RESULT
    )
    if(NOT VENV_RESULT EQUAL 0)
        message(FATAL_ERROR "uv failed to create Python 3.12 virtual environment")
    endif()
else()
    message(STATUS "Using existing hand-tracking Python virtual environment: ${PYTHON_EXE}")
endif()

if(NOT EXISTS "${PYTHON_EXE}")
    message(FATAL_ERROR "Expected Python executable does not exist: ${PYTHON_EXE}")
endif()

execute_process(
    COMMAND "${UV_EXECUTABLE}" pip install --python "${PYTHON_EXE}" -r "${REQUIREMENTS_FILE}"
    RESULT_VARIABLE PIP_RESULT
)
if(NOT PIP_RESULT EQUAL 0)
    message(FATAL_ERROR "uv failed to install hand-tracking Python requirements")
endif()

message(STATUS "Hand-tracking Python runtime ready: ${PYTHON_EXE}")
